name: botoholt_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_theme_switcher: ^2.0.7
  collection: ^1.16.0
  dio: ^4.0.6
  flag: ^6.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.0.8
  flutter_svg: ^1.1.6
  flutter_form_builder: ^7.7.0
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^8.3.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  functional_widget_annotation: ^0.10.0
  gap: ^2.0.0
  go_router: ^5.1.1
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  socket_io_client: ^2.0.0
  shared_preferences: ^2.0.15
  slang: ^3.5.0
  slang_build_runner: ^3.5.0
  slang_flutter: ^3.5.0
  tuple: ^2.0.1
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0
  
dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.0
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.0
  json_serializable: ^6.4.0

flutter_icons:
 image_path: "assets/dance/EZ.png"
 android: true
 web:
    generate: true
    image_path: "assets/dance/EZ.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
windows:
  generate: true
  image_path: "assets/dance/EZ.png"
  icon_size: 112


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  color_dark: "#313031"
  image_dark: assets/logo_dark.png
  android: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dance/